name: Validate Jekyll Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby 3.44
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'

    - name: Install dependencies
      run: bundle install

    - name: Build the site
      run: bundle exec jekyll build

    - name: Validate HTML
      run: |
        gem install html-proofer
        bundle exec jekyll build
        htmlproofer ./_site --disable-external

    - name: Validate CSS
      run: |
        gem install css-lint
        csslint ./_site/css

    - name: Validate Links
      run: |
        gem install html-proofer
        bundle exec jekyll build
        htmlproofer ./_site --check-html --check-external-hash